// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBliJ0cxQ3Se3mRf6HEF8vF0HoHl99hNAI',
    appId: '1:9548511374:web:59cfaf51fcb6bfd2b971df',
    messagingSenderId: '9548511374',
    projectId: 'com-exemplo-projeto1',
    authDomain: 'com-exemplo-projeto1.firebaseapp.com',
    storageBucket: 'com-exemplo-projeto1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_rKJ3dG-ssZUygx8EFbx01s5cL4gZAy0',
    appId: '1:9548511374:android:300a192c3acb4e4ab971df',
    messagingSenderId: '9548511374',
    projectId: 'com-exemplo-projeto1',
    storageBucket: 'com-exemplo-projeto1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOe2RB9Nr2HAZIGcuD-IYIaCJ18lL9IBM',
    appId: '1:9548511374:ios:5a1809a9e8166f39b971df',
    messagingSenderId: '9548511374',
    projectId: 'com-exemplo-projeto1',
    storageBucket: 'com-exemplo-projeto1.appspot.com',
    iosBundleId: 'com.example.projectmaneger',
  );
}
